ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
        sslPort: 8443
    security:
        ssl:
            keyStore: keystore.jks
            keyAlias: sampleAlias
            keyStorePassword: password
            privateKeyPassword: password